# SCALING, CUSTOMIZE TO YOUR DISPLAY
GLOBAL_SCALE = 1.2 # Customize scale of all objects in game
SCALE_WINDOW = 1.0 # Customize scale of window
SCALE_OBJECTS = GLOBAL_SCALE * SCALE_WINDOW # DONT TOUCH

# FOR CUSTOMIZE
FPS = 120

# BASE DIMENSIONS, DONT TOUCH
BASE_WIDTH = 975
BASE_HEIGHT = 975

# WINDOW SIZE, DONT TOUCH
WIDTH = int(BASE_WIDTH * SCALE_WINDOW)
HEIGHT = int(BASE_HEIGHT * SCALE_WINDOW)

# PLAYER START POSITION, HP RECTANGLE, DONT TOUCH
PLAYER_START_X = int(SCALE_WINDOW * (BASE_WIDTH - (100 * GLOBAL_SCALE)) / 2)
PLAYER_START_Y = int(SCALE_WINDOW * (BASE_HEIGHT - 125 * GLOBAL_SCALE))
PLAYER_MAX_HEALTH = 100
HP_HEIGHT = int(9 * SCALE_OBJECTS)

# ENEMY_START_POSITION, DONT_TOUCH
ENEMY_START_Y = int(15 * SCALE_OBJECTS)
ENEMY_BASE_HEALTH = 100

# MOVING
LASER_MOVE = int(9 * SCALE_OBJECTS)
PLAYER_MOVE = int(5 * SCALE_OBJECTS)

# CORRECTIONS
SHIP_CORRECTION = int(10 * SCALE_OBJECTS)
LASER_CORRECTION = int(45 * SCALE_OBJECTS)

# LASER
LASER_POWER = 10
