# SCALING, CUSTOMIZE TO YOUR DISPLAY, FPS
GLOBAL_SCALE = 1.2 # Customize scale of all objects in game
SCALE_WINDOW = 1.0 # Customize scale of window e.g. SCALE_WINDOW = 0.5 reduces window height and width by 1/2
SCALE_OBJECTS = GLOBAL_SCALE * SCALE_WINDOW
FPS = 120
# END OF CUSTOMIZE SECTION, ALL UPON IS UNTOUCHABLE

# BASE DIMENSIONS
BASE_WIDTH = 975
BASE_HEIGHT = 975

# WINDOW SIZE
WIDTH = int(BASE_WIDTH * SCALE_WINDOW)
HEIGHT = int(BASE_HEIGHT * SCALE_WINDOW)

# ICON SIZE
ICON_SIZE = 50

# PLAYER START POSITION, HP RECTANGLE
PLAYER_START_X = int(SCALE_WINDOW * (BASE_WIDTH - (100 * GLOBAL_SCALE)) / 2)
PLAYER_START_Y = int(SCALE_WINDOW * (BASE_HEIGHT - 125 * GLOBAL_SCALE))
PLAYER_LIVES = 3
PLAYER_MAX_HEALTH = 100
HP_HEIGHT = int(9 * SCALE_OBJECTS)

# ENEMY_START_POSITION
ENEMY_START_Y = int(15 * SCALE_OBJECTS)
ENEMY_BASE_HEALTH = 5
ENEMY_BASE_SPEED = 1 * SCALE_WINDOW
ENEMY_BASE_CHANCE = 500
ENEMY_COLLISION_HP = 20
SPAWN_ENEMY_TRIALS = 10
SPAWN_ENEMY_CHANCE = 500
SINGLE_SPAWN_PROB = 0.9
DOUBLE_SPAWN_PROB = 0.08
TRIPLE_SPAWN_PROB = 0.02


# MOVING
LASER_MOVE = int(9 * SCALE_OBJECTS)
PLAYER_MOVE = int(5 * SCALE_OBJECTS)

# CORRECTIONS
SHIP_CORRECTION = int(10 * SCALE_OBJECTS)
LASER_CORRECTION_PLAYER = int(45 * SCALE_OBJECTS)
LASER_CORRECTION_RG_X = int(-15 * SCALE_OBJECTS)
LASER_CORRECTION_RG_Y = int(2 * SCALE_OBJECTS)
LASER_CORRECTION_B_X = int(-25 * SCALE_OBJECTS)
LASER_CORRECTION_B_Y = int(12 * SCALE_OBJECTS)

# LASER
LASER_POWER = 10

# LEVELS
LEVEL_HP = 1
LEVEL_CHANCE = 20
LEVEL_SPEED = 0.05 * SCALE_OBJECTS
NEXT_LEVEL_BASE = 1.4
FIRST_LEVEL_SCORE = 3

# FONT
BEGIN_FONT_SIZE = int(75 * SCALE_WINDOW)
GAME_FONT_SIZE = int(55 * SCALE_WINDOW)
END_FONT_SIZE = int(190 * SCALE_WINDOW)
SCORE_X = int(760 * SCALE_WINDOW)
LIVES_X = int(10 * SCALE_WINDOW)

# END UI
END_HEIGHT_CORRECTION = int(120 * SCALE_WINDOW)
END_UI_SCALE = 0.85 * SCALE_WINDOW
BUTTON_Y = int(650 * SCALE_WINDOW)